export const MERCH = [
  {
    image: "/images/merch 11.png",
    title: "Akatsuki starter pack",
    description: "Kit containing all the Akatsuki gear",
    currentPrice: "200",
    oldPrice: "250",
    topSeller: true,
  },
  {
    image: "/images/merch 21.png",
    title: "Akatsuki pillows",
    description: "Even the Akatsuki takes naps",
    currentPrice: "10",
    oldPrice: "12",
    topSeller: false,
  },
  {
    image: "/images/merch 31.png",
    title: "Akatsuki kabuto",
    description: "The Akatsuki modern kabuto",
    currentPrice: "8",
    oldPrice: "10",
    topSeller: false,
  },
  {
    image: "/images/merch 41.png",
    title: "Akatsuki gamepad",
    description: "Built with pain destroy all opponents with each click",
    currentPrice: "100",
    oldPrice: "120",
    topSeller: false,
  },
  {
    image: "/images/merch 51.png",
    title: "Akatsuki Footy",
    description: "The world beneath your feet",
    currentPrice: "30",
    oldPrice: "45",
    topSeller: false,
  },
];
