import Head from "next/head";
import {
  About,
  Container,
  Help,
  Hero,
  Navbar,
  Text,
  Welcome,
} from "@/components";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <main>
        <Container>
          <Hero />
          <About />
          <Help />
          <Welcome />
          <br />
          <br />
          <br />
          <br />
          <br />
          <Text>
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Excepturi
            beatae explicabo praesentium animi deserunt dolore similique rerum
            eveniet incidunt. Labore corrupti culpa officia, modi iure magni,
            voluptate exercitationem inventore dolore ex voluptas nisi officiis
            nihil velit suscipit nulla mollitia. Debitis, corrupti. Commodi ad
            neque nulla velit quas adipisci quo vel aspernatur totam, placeat
            explicabo? Quos fugiat corrupti quis iure rem maiores eligendi
            voluptatibus dicta, reprehenderit quibusdam accusamus veniam impedit
            commodi soluta blanditiis doloremque. Temporibus consectetur, modi
            commodi nobis fuga ipsa ullam a pariatur earum ut tenetur deserunt
            et perspiciatis obcaecati itaque? Aperiam sit, vitae dolorem impedit
            quibusdam nesciunt provident veniam sunt. Deserunt ipsa ipsam odio
            quibusdam quo rerum, esse assumenda amet? Animi, nostrum consequatur
            sunt facere impedit excepturi quos accusantium odio nisi magni velit
            alias aliquid eius totam rem rerum, suscipit repudiandae, beatae
            deleniti laudantium perferendis vitae non! Quod modi corporis est
            laborum voluptatibus quasi facilis assumenda consequuntur. Soluta
            nulla esse, perferendis laborum modi harum autem illo, quibusdam
            labore animi, nisi officiis nemo tempore praesentium? Eligendi,
            velit voluptatibus earum praesentium aspernatur ipsum tempora
            sapiente totam vel. Mollitia, fugit. Nemo impedit quidem fugiat
            dolorem quo atque nisi nostrum, dignissimos iure perferendis est
            accusamus vel, alias id eius expedita voluptatem voluptatum ratione
            cumque debitis deleniti. Animi dicta suscipit illo ducimus
            necessitatibus! Explicabo, rerum
          </Text>
        </Container>
      </main>
    </>
  );
}
