import Head from "next/head";
import { Container } from "@/components";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Container>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio placeat,
          est minus quaerat rem, repellendus laboriosam fuga voluptas deleniti
          qui mollitia ipsa. Accusamus distinctio aut provident earum qui unde
          consequuntur!
        </Container>
      </main>
    </>
  );
}
